# Generated by Django 4.2.7 on 2026-04-01 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('objetivos', models.TextField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('grupo_muscular', models.CharField(choices=[('PEITO', 'Peito'), ('COSTAS', 'Costas'), ('PERNAS', 'Pernas'), ('OMBROS', 'Ombros'), ('BRACOS', 'Braços'), ('ABDOMEN', 'Abdômen'), ('CARDIO', 'Cardio'), ('OUTROS', 'Outros')], max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exercício',
                'verbose_name_plural': 'Exercícios',
                'ordering': ['grupo_muscular', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Mesociclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(2, '2x por semana'), (3, '3x por semana'), (4, '4x por semana'), (5, '5x por semana'), (6, '6x por semana'), (7, '7x por semana')], help_text='Frequência semanal')),
                ('data_inicio', models.DateField()),
                ('semanas_planejadas', models.IntegerField(default=4, help_text='Número de semanas planejadas')),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesociclos', to='core.aluno')),
            ],
            options={
                'verbose_name': 'Mesociclo',
                'verbose_name_plural': 'Mesociclos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TreinoEndurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(help_text='Número da semana')),
                ('dia_semana', models.IntegerField(choices=[(1, '1ª feira'), (2, '2ª feira'), (3, '3ª feira'), (4, '4ª feira'), (5, '5ª feira'), (6, '6ª feira'), (7, '7ª feira')], help_text='1=Segunda, 7=Domingo')),
                ('tipo', models.CharField(choices=[('CONTINUO', 'Contínuo'), ('INTERVALADO', 'Intervalado')], max_length=20)),
                ('velocidade_percentual_vmax', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual da velocidade máxima', max_digits=5, null=True)),
                ('tempo_minutos', models.IntegerField(blank=True, help_text='Duração em minutos', null=True)),
                ('n_sprints', models.IntegerField(blank=True, null=True)),
                ('tempo_sprint', models.IntegerField(blank=True, help_text='Tempo de cada sprint em segundos', null=True)),
                ('tempo_pausa', models.IntegerField(blank=True, help_text='Tempo de pausa em segundos', null=True)),
                ('realizado', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos_endurance', to='core.aluno')),
            ],
            options={
                'verbose_name': 'Treino de Endurance',
                'verbose_name_plural': 'Treinos de Endurance',
                'ordering': ['aluno', 'semana', 'dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Sessão A, Sessão B', max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('mesociclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='core.mesociclo')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['mesociclo', 'ordem'],
                'unique_together': {('mesociclo', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='IET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('velocidade_inicial', models.DecimalField(decimal_places=2, help_text='Velocidade inicial em km/h', max_digits=4)),
                ('velocidade_maxima', models.DecimalField(decimal_places=2, help_text='Velocidade máxima atingida em km/h', max_digits=4)),
                ('duracao_teste', models.DurationField(help_text='Duração total do teste')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testes_iet', to='core.aluno')),
            ],
            options={
                'verbose_name': 'IET - Teste Incremental em Esteira',
                'verbose_name_plural': 'IET - Testes Incrementais em Esteira',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ExercicioSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de execução')),
                ('series', models.IntegerField(default=3)),
                ('reps_por_serie', models.JSONField(default=list, help_text='Array com repetições por série')),
                ('pausa_segundos', models.IntegerField(default=60, help_text='Tempo de pausa entre séries em segundos')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios_sessao', to='core.exercicio')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios_sessao', to='core.sessao')),
            ],
            options={
                'verbose_name': 'Exercício da Sessão',
                'verbose_name_plural': 'Exercícios da Sessão',
                'ordering': ['sessao', 'ordem'],
                'unique_together': {('sessao', 'exercicio')},
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('massa_corporal', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Massa Corporal (kg)')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Altura (m)')),
                ('circunferencia_torax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('circunferencia_braco_direito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('circunferencia_braco_esquerdo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('circunferencia_cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('circunferencia_quadril', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('circunferencia_coxa_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('circunferencia_coxa_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('circunferencia_panturrilha_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('circunferencia_panturrilha_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dobra_peitoral', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dobra_axilar_media', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dobra_tricipital', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dobra_subescapular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dobra_abdominal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dobra_suprailiaca', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dobra_coxa', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='core.aluno')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='SetRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(help_text='Número da semana do mesociclo')),
                ('data', models.DateField()),
                ('numero_serie', models.IntegerField(help_text='Número da série (1, 2, 3...)')),
                ('carga_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Carga utilizada em kg', max_digits=5, null=True)),
                ('realizado', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('exercicio_sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets_realizados', to='core.exerciciosessao')),
            ],
            options={
                'verbose_name': 'Série Realizada',
                'verbose_name_plural': 'Séries Realizadas',
                'ordering': ['exercicio_sessao', 'semana', 'data', 'numero_serie'],
                'unique_together': {('exercicio_sessao', 'semana', 'data', 'numero_serie')},
            },
        ),
    ]
