# Generated by Django 4.2.7 on 2026-04-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exerciciosessao',
            unique_together=set(),
        ),
    ]
